controllers/OrderController.php
<?php

namespace app\controllers;

use app\components\interfaces\Access;
use app\helpers\PhotoHelper;
use app\helpers\PriceHelper;
use Yii;
use app\models\{Administrations, Agency, Order, Matrix, Constant, OrderCreate, OrderImage, search\OrderSearch, User};
use yii\base\DynamicModel;
use yii\filters\{VerbFilter, AccessControl};
use yii\web\{ForbiddenHttpException, Controller, HttpException, NotFoundHttpException, Response, UploadedFile};
use function GuzzleHttp\Psr7\mimetype_from_extension;
date_default_timezone_set('Europe/Moscow');

/**
 * OrderController implements the CRUD actions for Order model.
 */
class OrderController extends Controller implements Access
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
            'access' => [
                'class' => AccessControl::class,
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => [Constant::ROLE_ADMIN, Constant::ROLE_ADMINISTRATION],
                    ],
                    [
                        'allow' => true,
                        'actions' => ['index', 'download-photos', 'download-all-photos'],
                        'roles' => ['@'],
                    ],
                    [
                        'allow' => true,
                        'actions' => ['comment', 'send-to-agency'],
                        'roles' => [Constant::ROLE_PHOTO_MODERATOR],
                    ],
                    [
                        'allow' => true,
                        'actions' => ['change-status', 'schedule', 'update-description', 'calculate-photograph-price'],
                        'roles' => [Constant::ROLE_ADMIN_OF_PHOTOGRAPHER],
                    ],
                    [
                        'allow' => true,
                        'actions' => ['schedule', 'fail'],
                        'roles' => [Constant::ROLE_PHOTOGRAPHER],
                    ],
                    [
                        'allow' => true,
                        'actions' => ['reject', 'upload-photos'],
                        'roles' => [Constant::ROLE_PHOTOGRAPHER, Constant::ROLE_PHOTO_MODERATOR],
                        'matchCallback' => function ($rule, $action) {
                            $model = $this->findModel(Yii::$app->request->get('id'));
                            return in_array($model->status, [Constant::ORDER_STATUS_EXECUTING, Constant::ORDER_STATUS_MODERATION]);
                        }
                    ],
                    [
                        'allow' => true,
                        'actions' => ['back-to-work', 'create', 'calculate-agency-price'],
                        'roles' => [Constant::ROLE_REAL_ESTATE_AGENCY],
                    ],
                    [
                        'actions' => ['update', 'delete'],
                        'allow' => true,
                        'roles' => [Constant::ROLE_REAL_ESTATE_AGENCY],
                        'matchCallback' => function ($rule, $action) {
                            $model = $this->findModel(Yii::$app->request->get('id'));
                            return ($model->agency_id == Yii::$app->user->identity->agency->id) && ($model->status == Constant::ORDER_STATUS_NEW);
                        }
                    ],
                    [
                        'actions' => ['view'],
                        'allow' => true,
                        'roles' => ['@'],
                        'matchCallback' => function ($rule, $action) {
                            return $this->checkAccess(Yii::$app->request->get('id'));
                        }
                    ],
                ],
            ],
        ];
    }

    /**
     * Lists all Order models.
     * @param null $ready
     * @return string
     */
    public function actionIndex($ready = null)
    {
        $this->layout = 'main_without_container';
        $searchModel = new OrderSearch();
        $role = Yii::$app->user->identity->getRole();

        if (in_array(Yii::$app->user->identity->getRole(), [Constant::ROLE_ADMIN_OF_PHOTOGRAPHER, Constant::ROLE_REAL_ESTATE_AGENCY]) &&
            $ready !== null) {
            if ($ready == 0) {
                $searchModel->status = Constant::notReadyOrderStatuses();
            } else {
                $searchModel->status = Constant::readyOrderStatuses();
            }
        }

        if (($role == Constant::ROLE_PHOTO_MODERATOR) && $ready !== null) {
            if ($ready == 0) {
                $searchModel->status = [Constant::ORDER_STATUS_EXECUTING, Constant::ORDER_STATUS_MODERATION];
            } else {
                $searchModel->status = Constant::ORDER_STATUS_DOWNLOADED;
            }
        }

        $dataProvider = $searchModel->search(Yii::$app->request->queryParams, $ready);

        return $this->render($this->getViewFile($this->action->id), [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Расписание
     * @return string
     */
    public function actionSchedule()
    {
        $identity = Yii::$app->user->identity;

        $query = (new OrderSearch())->searchSchedule();

        ($identity->getRole() == Constant::ROLE_PHOTOGRAPHER) && $query->andWhere(['photographer_id' => $identity->photographer->id]);
        $modelsByPhotographer = [];

        foreach ($query->all() as $model) {
            $modelsByPhotographer[$model->photographer_id][] = $model;
        }

        return $this->render('schedule', compact('modelsByPhotographer'));
    }

    /**
     * Displays a single Order model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Order model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     *
     * @return mixed
     */
    public function actionCreate()
    {
        $role = Yii::$app->user->identity->getRole();
        if ($role == Constant::ROLE_ADMIN || $role == Constant::ROLE_ADMINISTRATION) {
            $model = new OrderCreate();
        } else {
            $model = new Order();
            $model->scenario = OrderCreate::SCENARIO_CREATE_UPDATE;
        }
        ($role == Constant::ROLE_REAL_ESTATE_AGENCY) && $model->agency_id = Yii::$app->user->identity->agency->id;

        if ($model->load(Yii::$app->request->post()) && $model->validate()) {

            if (!empty($model->zone) && !empty($model->room_qnt_type)) {
                if ($role == Constant::ROLE_REAL_ESTATE_AGENCY) {
                    $model->price_agency = (new PriceHelper())->calculatePrice('agency_id', $model);
                }
                if ($model->photographer_id != null) {
                    $model->price = (new PriceHelper())->calculatePrice('photographer_id', $model);
                }
            }
            $model->save(false);
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Order model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $model->scenario = Order::SCENARIO_CREATE_UPDATE;

        if ($model->load(Yii::$app->request->post()) && $model->validate()) {

            if (!empty($model->zone) && !empty($model->room_qnt_type)) {
                if ($model->photographer_id != null) {
                    $model->price = (new PriceHelper())->calculatePrice('photographer_id', $model);
                }
            }
            $model->save(false);
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    public function actionChangeStatus($id)
    {
        $model = $this->findModel($id);

        if (!Yii::$app->user->can(Constant::ROLE_ADMIN) && $model->isReady()) {
            throw new HttpException(400, 'Нельзя изменить статус готовой заявки');
        }
        $model->scenario = Order::SCENARIO_CHANGE_STATUS;

        //===========ДЛЯ КАРТЫ===============
        $orderModels = (new OrderSearch())->searchOrdersMap();
        $orders = [];

        $colorQnt = count(Constant::YMAP_ICON_PRESETS);
        foreach ($orderModels as $orderModel) {
            if (!isset($orders[$orderModel->photographer_id]['color'])) {
                $orders[$orderModel->photographer_id]['color'] = Constant::YMAP_ICON_PRESETS[count($orders) % $colorQnt];
            }
            $orders[$orderModel->photographer_id]['models'][] = $orderModel;

        }
        //=====================================

        if ($model->load(Yii::$app->request->post()) && $model->validate()) {

            if ($model->status == 'status-failed') {
                $model->price_agency = $model->price_agency / 2;
            }

            if ($model->status == 'status-rejected') {
                $model->price_agency = 0;
                $model->price = 0;
            }

            $model->save(false);
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('forms/_form_status', compact('model', 'orders'));
    }

    /**
     * @return bool|mixed|null
     * @throws NotFoundHttpException
     */

views/order/create.php
<?php

use yii\helpers\Html;
use app\models\Constant;

/* @var $this yii\web\View */
/* @var $model app\models\Order */

$url = !in_array(Yii::$app->user->identity->getRole(), [Constant::ROLE_REAL_ESTATE_AGENCY, Constant::ROLE_ADMIN_OF_PHOTOGRAPHER]) ? ['index'] : ['index', 'ready' => false];
$this->title = 'Создать заявку';
$this->params['breadcrumbs'][] = ['label' => 'Заявки', 'url' => $url];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="order-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('forms/_form', [
        'model' => $model,
    ]) ?>

</div>

views/order/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\search\OrderSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Заявки';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="order-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Создать Заявку', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'id',
            'agency_id',
            'realtor',
            'status',
            'execution_date_from',
            //'execution_date_to',
            //'photographer_id',
            //'created_at',
            //'updated_at',

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>


</div>

views/order/map-by-statuses.php
<?php
use yii\helpers\Html;
use app\models\Constant;

$this->title = 'Карта по статусам';
$this->registerJsFile('https://api-maps.yandex.ru/2.1/?lang=ru_RU&apikey=30071976-3b4b-46b5-9531-5d5594e49e96&width=640&height=480');

$dataData = array(
    'type' => 'FeatureCollection',
    'features' => [],
);

$mapJs = '';
$isNsk = true;


$mapJs .= " }); ";

//Добавляем код инициализации карты
//Добавляем в конце для возможности изменения зума
$mapJs = "ymaps.ready(function () {
    var myMap = new ymaps.Map('map', {
            center: [55.010317, 82.950156],
            zoom: " . ($isNsk ? 11 : 6) . ",
        }, {
            searchControlProvider: 'yandex#search'
        }),
        objectManager = new ymaps.ObjectManager({
            // Чтобы метки начали кластеризоваться, выставляем опцию.
            clusterize: true,
            // ObjectManager принимает те же опции, что и кластеризатор.
            gridSize: 32,
            clusterDisableClickZoom: true
        });
        
        myMap.geoObjects.add(objectManager);
        $.ajax({
            url: 'get-json-object-for-map'
        }).done(function(data) {
            console.log(data);
            objectManager.add(data);
        });
        
        
        // Создаём макет содержимого.
        MyIconContentLayout = ymaps.templateLayoutFactory.createClass(
            '<div style=\"color: #FFFFFF; font-weight: bold;\">$[properties.iconContent]</div>'
        ); " . $mapJs;
$this->registerJs($mapJs);
?>

<h1><?=$this->title?></h1>

<div>
    <?=Html::button(Constant::orderStatuses(true)[Constant::ORDER_STATUS_NEW],
        ['class' => 'btn-color-blueStretchyIcon colored-status'])?>

    <?=Html::button(Constant::orderStatuses(true)[Constant::ORDER_STATUS_PRELIM_CALL],
        ['class' => 'btn-color-violetStretchyIcon colored-status'])?>

    <?=Html::button(Constant::orderStatuses(true)[Constant::ORDER_STATUS_MISSED_CALL_1],
        ['class' => 'btn-color-yellowStretchyIcon colored-status'])?>

    <?=Html::button(Constant::orderStatuses(true)[Constant::ORDER_STATUS_MISSED_CALL_2],
        ['class' => 'btn-color-yellowStretchyIcon colored-status'])?>

</div>

<p>
    <div id="map" style="width: 100%; height: 500px; padding: 0; margin: 0;"></div>
</p>

views/order/schedule.php
<?php
use yii\helpers\Html;

$this->title = 'Расписание';
?>

<h1><?= $this->title ?></h1>
<div class="row">
    <div class="col-md-10">
        <table class="table table-bordered schedule-table">
            <?php foreach ($modelsByPhotographer as $key => $modelsArray): ?>
                <tr class="row-photographer">
                    <td><span class="schedule-photographer"
                              data-id="<?= $key ?>"><?= $modelsArray[0]->photographer->fio ?></span>
                        (<?= count($modelsArray) ?>)
                    </td>
                    <td></td>
                </tr>
                <?php foreach ($modelsArray as $model): ?>
                        <tr data-photographer="<?= $key ?>">
                            <td><?= $model->period ?></td>
                            <td><?=Html::a("Заявка №$model->number", ['order/view', 'id' => $model->id])?>, <?=$model->address?></td>
                        </tr>
                <?php endforeach; ?>
            <?php endforeach; ?>
        </table>
    </div>
</div>

<?php
$js = <<<JS
$(document).on('click','.schedule-photographer', function(e) {
       let id = $(this).attr('data-id');
       $('tr[data-photographer="' + id + '"]').fadeToggle();
    });

JS;
$this->registerJs($js);
?>

views/order/update.php
<?php

use yii\helpers\Html;
use app\models\Constant;

/* @var $this yii\web\View */
/* @var $model app\models\Order */

$url = !in_array(Yii::$app->user->identity->getRole(), [Constant::ROLE_REAL_ESTATE_AGENCY, Constant::ROLE_ADMIN_OF_PHOTOGRAPHER]) ? ['index'] : ['index', 'ready' => true];
$this->title = 'Редактировать заявку №: ' . $model->number;
$this->params['breadcrumbs'][] = ['label' => 'Заявки', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => "№$model->number", 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Редактировать ';
?>
<div class="order-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('forms/_form', [
        'model' => $model,
    ]) ?>

</div>

views/order/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use app\models\Constant;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Order */

$url = in_array(Yii::$app->user->identity->getRole(), [Constant::ROLE_REAL_ESTATE_AGENCY, Constant::ROLE_ADMIN_OF_PHOTOGRAPHER]) ?
    ['index', 'ready' => $model->isReady()] :
    ['index'];
$this->title = 'Заявка № ' . $model->number;
$this->params['breadcrumbs'][] = ['label' => 'Заявки', 'url' => $url];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);

$attributes = [];
if (in_array(YIi::$app->user->identity->getRole(), [Constant::ROLE_ADMIN, Constant::ROLE_ADMIN_OF_PHOTOGRAPHER, Constant::ROLE_ADMINISTRATION])) {
    $attributes = [
        'id',
        'number',
        [
            'attribute' => 'agency.name',
            'label' => 'АН'
        ],
        'realtor',
        [
            'attribute' => 'status',
            'value' => function ($model) {
                return $model->getStatus();
            }
        ],
        'roomQntType',
        'zone',
        'address',
        'description:raw',
        'description_admin:raw',
        'client_name',
        'phone_number',
        [
            'attribute' => 'call_history',
            'visible' => (Yii::$app->user->identity->getRole() == Constant::ROLE_ADMIN_OF_PHOTOGRAPHER ||
                Yii::$app->user->identity->getRole() == Constant::ROLE_ADMIN)
        ],
        [
            'attribute' => 'execution_date_from',
            'label' => 'Дата исполнения',
            'format' => 'raw',
            'value' => function ($model) {
                return $model->execution_date_from . ' &mdash; ' . $model->execution_date_to;
            }
        ],
        [
            'attribute' => 'planing_contact_date',
            'value' => function ($model) {
                return $model->planing_contact_date;
            }
        ],
        [
            'attribute' => 'changing_status_date',
            'value' => function ($model) {
                return $model->changing_status_date;
            }
        ],
        'price:currency',
        [
            'attribute' => 'price_agency',
            'format' => 'currency',
            'visible' => Yii::$app->user->can('admin')
        ],
        'photographer.fio',
        'photographer_comment:raw',
        'downloaded:boolean',
        'created',
        'updated',
        [
            'label' => 'Фото',
            'format' => 'raw',
            'visible' => $model->images,
            'value' => function ($model) {
                return $this->context->renderPartial('parts/images', compact('model'));
            }
        ]
    ];
}

if (Yii::$app->user->identity->getRole() == Constant::ROLE_REAL_ESTATE_AGENCY) {
    $attributes = [
        'number',
        'address',
        'roomQntType',
        'zone',
        'client_name',
        'phone_number',
        'realtor',
        'description',
        'price_agency',
        [
            'attribute' => 'status',
            'value' => function ($model) {
                return $model->getStatus();
            }
        ],
        [
            'attribute' => 'photographer_comment',
            'format' => 'raw',
            'visible' => $model->status === Constant::ORDER_STATUS_DOWNLOADED
        ],
        [
            'label' => 'Фото',
            'format' => 'raw',
            'visible' => in_array($model->status, [Constant::ORDER_STATUS_DOWNLOADED, Constant::ORDER_STATUS_FAILED]) && $model->images,
            'value' => function ($model) {
                return $this->context->renderPartial('parts/images', compact('model'));
            }
        ]
    ];
}
if (Yii::$app->user->identity->getRole() == Constant::ROLE_PHOTOGRAPHER) {
    $attributes = [
        'number',
        [
            'attribute' => 'status',
            'value' => function ($model) {
                return $model->getStatus();
            }
        ],
        'address',
        'description_admin',
        [
            'attribute' => 'execution_date_from',
            'label' => 'Дата исполнения',
            'format' => 'raw',
            'value' => function ($model) {
                return $model->execution_date_from . ' &mdash; ' . $model->execution_date_to;
            }
        ],
        'phone_number',
        'price:currency',
        //'description_admin:raw',
        'photographer_comment:raw',
        [
            'label' => 'Фото',
            'format' => 'raw',
            'visible' => $model->images,
            'value' => function ($model) {
                return $this->context->renderPartial('parts/images', compact('model'));
            }
        ]
    ];
}

if (Yii::$app->user->identity->getRole() == Constant::ROLE_PHOTO_MODERATOR) {
    $attributes = [
        'number',
        [
            'attribute' => 'status',
            'value' => function ($model) {
                return $model->getStatus();
            }
        ],
        'address',
        'photographer_comment:raw',
        'downloaded:boolean',
        [
            'label' => 'Фото',
            'format' => 'raw',
            'visible' => $model->images,
            'value' => function ($model) {
                return $this->context->renderPartial('parts/images', compact('model'));
            }
        ]
    ];
}

?>
<div class="order-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->user->can(Constant::ROLE_ADMIN)): ?>
        <p>
            <?= Html::a('Редактировать', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
            <?= Html::a('Удалить', ['delete', 'id' => $model->id], [
                'class' => 'btn btn-danger',
                'data' => [
                    'confirm' => 'Вы уверены?',
                    'method' => 'post',
                ],
            ]) ?>
        </p>
    <?php endif; ?>

    <?php if (Yii::$app->user->identity->getRole() == Constant::ROLE_PHOTOGRAPHER): ?>
        <p>
            <?= Html::a('Добавить фото/комментарий', ['order/upload-photos', 'id' => $model->id], ['class' => 'btn btn-info']) ?>
            <?= ($model->status != Constant::ORDER_STATUS_FAILED) ? Html::a('Ложная заявка', ['order/fail', 'id' => $model->id], ['class' => 'btn btn-danger']) : null ?>
        </p>

    <?php endif; ?>

    <?php if (Yii::$app->user->identity->getRole() == Constant::ROLE_PHOTO_MODERATOR): ?>
        <p>
            <?= Html::a('Отправить АН', ['order/send-to-agency', 'id' => $model->id], ['class' => 'btn btn-info', 'disabled' => empty($model->images)]) ?>
            <?= Html::a('Добавить фото / Редактировать', ['order/upload-photos', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        </p>

    <?php endif; ?>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => $attributes,
    ]) ?>

    <?php if (Yii::$app->user->identity->getRole() == Constant::ROLE_REAL_ESTATE_AGENCY): ?>

        <div class="pull-right">
            <?= Html::a('Создать следующую заявку ', ['order/create'], ['class' => 'btn btn-success']) ?>
        </div>

    <?php endif; ?>


</div>